import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Grid } from '@mui/material'
import Solutions from '@/component/Solutions'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Squarefix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Inter+Tight:wght@300;400;500;600;700&display=swap" rel="stylesheet"></link>
      </Head>
      <main style={{
        margin: '0 2%',

      }}>
        <Grid container>
          <Grid item lg={6} md={6} sm={12} xs={12}>
            <h1 className={styles.mainHeading}>We manage your IT, so you can manage your business.
            </h1>
          </Grid>
          <Grid item lg={6} md={6} sm={12} xs={12}>

          </Grid>
          <Grid item lg={5} md={5} sm={12} xs={12}>

            <h1 className={styles.subHeading}>Take charge of your business continuity with innovative IT solutions
            </h1>
            <div>
              <a className={`${styles.btn} ${styles.mainHeadingBtn}`}>Schedule a Free Consultation</a>
              <a className={`${styles.secondbtn}`}>Services </a>
            </div>

          </Grid>
          <Grid item lg={7} md={7} sm={12} xs={12}>
            <h1 className={styles.subHeading}>

            </h1>
          </Grid>
        </Grid>
        <Grid container justifyContent={'center'}>
          <Grid item lg={3} md={3} sm={6} xs={6}>
            <div className={styles.infoContainer}>
              <p className={styles.infoTextFirst}>
                20
                Years
              </p>
              <p className={styles.infoTextSecond}>
                Proven Track Record</p>
            </div>
          </Grid>
          <Grid item lg={3} md={3} sm={6} xs={6}>
            <div className={styles.infoContainer}>
              <p className={styles.infoTextFirst}>
                98%
              </p>
              <p className={styles.infoTextSecond}>
                Customer Satisfaction
              </p>
            </div>
          </Grid>
          <Grid item lg={3} md={3} sm={6} xs={6}>
            <div className={styles.infoContainer}>
              <p className={styles.infoTextFirst}>
                1,500
                Projects

              </p>
              <p className={styles.infoTextSecond}>
                We Have Completed


              </p>
            </div>
          </Grid>
          <Grid item lg={3} md={3} sm={6} xs={6}>
            <div className={styles.infoContainer}>
              <p className={styles.infoTextFirst}>
                3
                Mins
              </p>
              <p className={styles.infoTextSecond}>
                Average Answer Time

              </p>
            </div>
          </Grid>
        </Grid>
        <Solutions />




      </main >
    </>
  )
}
